site_name: utop1an
site_author: Chunjie Liu
site_description: Knowledge Wiki, notebook....

nav: 
  - Home: index.md
  - About Me: about.md
  - Test:
    - Test1: test/test1.md
    - Test2: test/test2.md

plugins:
  - search

extra:
  generator: false

extra_css:
  - assets/stylesheets/extra.css

theme: 
  custom_dir: docs/overrides
  name: material
  features: 
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Nunito
    code: Oxygen Mono
  palette: 
    - scheme: default
 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
    
      toggle:
        icon: material/brightness-4
        name: Switch to light mode